[global]
log_level = "WARN"

[transcribe]
backend = "whisper"
model = "Systran/faster-whisper-large-v3"
device = "auto"
compute_type = "float32"
language = "auto"
clean_audio = true
vad_filter = true
vad_threshold = 0.35
vad_min_silence_ms = 250
beam_size = 8
# Leave best_of unset to rely on beam search
temperature = 0.2
initial_prompt_file = "prompts/initial_prompt.txt"
word_timestamps = true
max_line_words = 12
min_line_words = 4
max_line_duration = 5.0
max_gap = 0.8
cpu_threads = 8
num_workers = 4
chunk_length = 30

[build_video]
burn = "force"
font_size = 40
font_file = ""
subtitle_language = "und"
